[package]
name = "annonars"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust template repository"
license = "Apache-2.0"
homepage = "https://github.com/bihealth/annonars"
readme = "README.md"
autobins = false

[lib]
name = "annonars"
path = "src/lib.rs"

[[bin]]
name = "annonars"
path = "src/main.rs"

[dependencies]
boolvec = "0.2.6"
byteorder = "1.4.3"
log = { version = "0.4"}
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features=["preserve_order"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = {version = "0.3"}
clap = { version = "4.1", features = ["derive", "env"] }
clap-verbosity-flag = {version = "2.0"}
anyhow = { version = "1.0" }
strum = { version = "0.24", features = ["strum_macros", "derive"] }
rayon = { version = "1.7" }
indicatif = { version = "0.17", features = ["rayon"] }
flate2 = { version = "1.0" }
bgzip = { version = "0.3" }
noodles-bgzf = { version = "0.21" }
noodles-tabix = { version = "0.21" }
noodles-csi = "0.17.0"
noodles-core = "0.11.0"
hgvs = { version = "0.7" }
prost = "0.11"
csv = "1.2.1"
noodles-vcf = "0.29.0"
noodles-util = { version = "0.11.0", features = ["variant"] }

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
env_logger = "0.10"
insta = { version = "1.29", features = ["yaml"] }
log = "0.4"
pretty_assertions = "1.3"
temp_testdir = "0.2"
test-log = "0.2"
tracing-subscriber = {version = "0.3" }
